### ISSUE TITLE
DB connection through psql issue

### ISSUE THREAD

**Issue by Chitrasree24** [opentelekomcloud-docs/relational-database-service#34]
Hi,

I'm facing issues while connecting to database through psql and getting error as below-

postgres@evosfncll1065 ~]$ psql
psql: /tcg/app/postgresql/postgresql-14.4/lib/libpq.so.5: no version information available (required by psql)
psql: /tcg/app/postgresql/postgresql-14.4/lib/libpq.so.5: no version information available (required by psql)
**psql: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?**

Kindly provide a solution/steps to follow to resolve the above issue.

**Comment by lboka** [comment]
Hi [Chitrasree24](https://github.com/Chitrasree24)
First of all I apologize for the late answer. 
This platform provides possibility to report a bug on our Documentation portal - in order to improve the quality of our documentation. It should not be used to solve issues with the services or recourses. 
Issues like that should be reported in different channel.
In case your question is still valid and you still facing this issue, please contact: **service@open-telekom-cloud.com** 
Thank you for understanding.
